# Generated by Django 2.2 on 2020-04-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200411_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='作者', related_name='book_author', to='books.Author', verbose_name='作者'),
        ),
    ]
